server:
  port: 8080

pages:
  - name: Home
    columns:
      - size: small
        widgets:
          - type: clock
            hour-format: 24h
          - type: calendar
          - type: monitor
            cache: 1m
            title: Services
            sites:
              - title: Polidomus
                url: https://polidomus.polione.xyz
                icon: si:homeassistant
              - title: "Polidomus: Nabu"
                url: https://5trb03zqo4oyaiij7d43id6lyui5xsvb.ui.nabu.casa
                icon: si:homeassistant
          - type: releases
            show-source-icon: true
            repositories:
              - advplyr/audiobookshelf
              - glanceapp/glance
              - garethgeorge/backrest
              - immich-app/immich

      - size: full

        widgets:
          - type: search
            search-engine: google
          - type: bookmarks
            groups:
              - title: Entertainment
                links:
                  - title: YouTube
                    url: https://www.youtube.com/
                    icon: si:youtube
                  - title: Plex
                    url: https://app.plex.tv/desktop/#!/
                    icon: si:plex
                  - title: Overleaf
                    url: https://www.overleaf.com/project
                    icon: si:overleaf


              - title: AI
                color: 10 70 50
                links:
                  - title: ChatGPT
                    url: https://chat.openai.com/
                    icon: si:openai
                  - title: Claude
                    url: https://claude.ai/
                    icon: si:anthropic


              - title: Pirate
                color: 200 50 50
                links:
                  - title: Paradisoditutti
                    url: https://imperodeisogni.com/
                  - title: DDLItalia
                    url: https://www.ddlitalia.biz/
                  - title: CorsaroNero
                    url: https://ilcorsaronero.link/
                  - title:  Mircrew
                    url: https://mircrew-releases.org/
                  - title: Torrentleech
                    url: https://www.torrentleech.org

          - type: rss
            limit: 15
            collapse-after: 5
            cache: 3h
            feeds:
              - url: https://ciechanow.ski/atom.xml
              - url: https://www.joshwcomeau.com/rss.xml
                title: Josh Comeau
              - url: https://samwho.dev/rss.xml
              - url: https://awesomekling.github.io/feed.xml
              - url: https://ishadeed.com/feed.xml
                title: Ahmad Shadee
              - url: https://feeds.macrumors.com/MacRumors-All
                title: Mac Rumors
              # - url: https://www.ilpost.it/feed
              #   title: Il Post


          - type: videos
            channels:
              - UCR-DXc1voovS8nhAvccRZhg # Jeff Geerling
              - UCXuqSBlHAE6Xw-yeJA0Tunw # Linus Tech Tips
              - UCnDDucQDLncrauOCmanCIgw # Morro linux
              - UCO2x-p9gg9TLKneXlibGR7w # Snazzy
              - UCoyoYGVhKzfs1vCgAGoaOuw # Saggiamente
              - UC4V3oCikXeSqYQr0hBMARwg # breaking italy

      - size: small
        widgets:
          - type: docker-containers
            hide-by-default: true
          - type: weather
            location: Milan, Italy
          - type: weather
            location: Bologna, Italy
          - type: markets
            markets:
              - symbol: SPY
                name: S&P 500
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: NVDA
                name: NVIDIA
              - symbol: AAPL
                name: Apple
              - symbol: MSFT
                name: Microsoft
              - symbol: GOOGL
                name: Google
              - symbol: AMD
                name: AMD
              - symbol: RDDT
                name: Reddit
